---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  storageClassName: {{ .Values.pvc.sc }}
  accessModes:
  - {{ .Values.pvc.access }}
  resources:
    requests:
      storage: {{ .Values.pvc.volume }}
