---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "deploySpec.labels" . | nindent 4 }}
  type: {{ .Values.service.type }}
